Am.Ui.Web/Models/ErrorViewModel.cs
namespace Am.Ui.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Am.Ui.Web/Controllers/FlightController.cs
using AM.ApllicationCore.Interface;
using AM.ApplicationCore.Domain;
using AM.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Am.Ui.Web.Controllers
{
    public class FlightController : Controller
    {
        IServicesFlight servicesFlight; 
        IServicePlane servicePlane;
        public FlightController(IServicesFlight servicesFlight,IServicePlane servicePlane)
        {
            this.servicesFlight = servicesFlight;  
            this.servicePlane = servicePlane;   
        }

        // GET: FlightController
        public ActionResult Index(DateTime? dateDepart)
        {
            if (dateDepart == null)
                return View(servicesFlight.GetAll());
            else
                return View(servicesFlight.GetMany(f => f.FlightDate.Date.Equals(dateDepart)));
        }

        // GET: FlightController/Details/5
        public ActionResult Details(int id)
        {
            return View(servicesFlight.GetById(id));
        }

        // GET: FlightController/Create
        public ActionResult Create()
        {
            ViewBag.PlaneId = new SelectList(servicePlane.GetAll(), "PlaneId", "Information");
            return View();
        }

        // POST: FlightController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Flight collection,IFormFile Airline)
        {
            try
            {
                if (Airline != null)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(),

                    "wwwroot", "Uploads", Airline.FileName);

                    Stream stream = new FileStream(path, FileMode.Create);
                    Airline.CopyTo(stream);
                    collection.Airline = Airline.FileName;
                }

                servicesFlight.Add(collection);
                servicesFlight.Commit();
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(servicesFlight.GetById(id)); 

        }

        // POST: FlightController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Flight collection)
        {
            try
            {
                servicesFlight.Update(collection);
                servicesFlight.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(servicesFlight.GetById (id));
        }

        // POST: FlightController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Flight collection)
        {
            try
            {
                servicesFlight.Delete(collection);
                servicesFlight.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Am.Ui.Web/Controllers/HomeController.cs
using Am.Ui.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Am.Ui.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Am.Ui.Web/Controllers/PlaneController.cs
using AM.ApllicationCore.Domain;
using AM.ApllicationCore.Interface;
using AM.ApllicationCore.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Am.Ui.Web.Views
{
    public class PlaneController : Controller
    {IServicePlane servicePlane;
        public PlaneController( IServicePlane servicePlane)
        {
            this.servicePlane = servicePlane;
        }
        // GET: PlaneController
        public ActionResult Index()
        {
            return View(servicePlane.GetAll());
        }

        // GET: PlaneController/Details/5
        public ActionResult Details(int id)
        {
            return View(servicePlane.GetById(id));
        }

        // GET: PlaneController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Plane collection)
        {
            try
            {
                servicePlane.Add(collection);
                servicePlane.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PlaneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaneController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PlaneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Am.Ui.Web/Views/Flight/Create.cshtml
@model AM.ApplicationCore.Domain.Flight

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Airline" class="control-label"></label>
                <input type="file" name="Airline" class="form-control" />
                <span asp-validation-for="Airline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <select asp-for="PlaneId" class ="form-control" asp-items="ViewBag.PlaneId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Am.Ui.Web/Views/Flight/Delete.cshtml
@model AM.ApplicationCore.Domain.Flight

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlightDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EffectiveArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EffectiveArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MyPlane)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MyPlane.PlaneId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Airline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Airline)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlightId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Am.Ui.Web/Views/Flight/Edit.cshtml
@model AM.ApplicationCore.Domain.Flight

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departure" class="control-label"></label>
                <input asp-for="Departure" class="form-control" />
                <span asp-validation-for="Departure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightDate" class="control-label"></label>
                <input asp-for="FlightDate" class="form-control" />
                <span asp-validation-for="FlightDate" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="FlightId" />
            <div class="form-group">
                <label asp-for="EffectiveArrival" class="control-label"></label>
                <input asp-for="EffectiveArrival" class="form-control" />
                <span asp-validation-for="EffectiveArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDuration" class="control-label"></label>
                <input asp-for="EstimatedDuration" class="form-control" />
                <span asp-validation-for="EstimatedDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Airline" class="control-label"></label>
                <input asp-for="Airline" class="form-control" />
                <span asp-validation-for="Airline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneId" class="control-label"></label>
                <select asp-for="PlaneId" class="form-control" asp-items="ViewBag.PlaneId"></select>
                <span asp-validation-for="PlaneId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Am.Ui.Web/Views/Flight/Index.cshtml
@model IEnumerable<AM.ApplicationCore.Domain.Flight>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1> 

<p>
    <a asp-action="Create">Create New</a>
</p> 

<form asp-action="index">  
    <fieldset>
        <legend> 
            Recherche
        </legend>  
        Saisir une date De recherche
        <input type="Date" name="dateDepart" />
        <input type="submit" name="search" />

    </fieldset>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveArrival)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MyPlane)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Airline)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveArrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MyPlane.PlaneId)
            </td>
            <td>

                <img src="~/Uploads/@item.Airline" width="50" height="50"> 
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FlightId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FlightId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FlightId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Am.Ui.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Travail de Mariem Aljene  </h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Am.Ui.Web/Views/Plane/Create.cshtml
@model AM.ApllicationCore.Domain.Plane

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Plane</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManuFactureDate" class="control-label"></label>
                <input asp-for="ManuFactureDate" class="form-control" />
                <span asp-validation-for="ManuFactureDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneType" class="control-label"></label>
                <select asp-for="PlaneType" class="form-control" asp-items="Html.GetEnumSelectList<AM.ApllicationCore.Domain.PlaneType>()"> </select>
                <span asp-validation-for="PlaneType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Am.Ui.Web/Views/Plane/Index.cshtml
@model IEnumerable<AM.ApllicationCore.Domain.Plane>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@foreach (var item in Model)
{
    @Html.Partial("_Details",item) ;
}

Am.Ui.Web/Views/Plane/_Details.cshtml
@model AM.ApllicationCore.Domain.Plane

<div>
    <h4>Plane</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManuFactureDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManuFactureDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaneType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaneType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PlaneId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Am.Ui.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Am.Ui.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Am.Ui.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Am.Ui.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="Index">Flights</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Am.Ui.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>